apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-Multiple
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: dileepchi/k8s:ale
      ports:
        - containerPort: 8081
    - name: web-ctr2
      image: dileepchi/k8s:ale
      ports:
        - containerPort: 8080